# src/main/resources/META-INF/mods.toml
#

modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://gituhb.com/antiphysika/REPO/issues"

[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://antiphysika.dev/minecraft/mods/${mod_id}/updates.json"
#displayURL="https://antiphysika.dev/minecraft/mods/${mod_id}"
#logoFile="${mod_id}.png"
#credits=""
authors="${mod_authors}"
#displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
  modId="forge" #mandatory
  mandatory=true #mandatory
  versionRange="${forge_version_range}" #mandatory
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#
# vim: ts=2 sw=2 et fdm=marker :
